name: optimus_opost
description: A new Flutter project.
publish_to: "none"

version: 1.5.4+10

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  url_launcher: ^6.2.6
  flutter_html: ^3.0.0-beta.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  crypto: ^3.0.3

  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  firebase_analytics: ^11.5.2
  cloud_firestore: ^5.6.11

  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  # Code generation ONLY
  flutter_gen: ^5.12.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
  remove_alpha_ios: true
